
load_from_hub: False
hub_dataset_name: 'name'

train_file_path: 'data/csob/train.csv'
val_file_path: 'data/csob/val.csv'
test_file_path: 'data/csob/test.csv'
delimiter: ','

text_column_name: 'text'
label_column_name: 'category'